---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-custom
  template:
    metadata:
      labels:
        app: monitoring-custom
    spec:
      containers:
        - name: main
          image: ghcr.io/kyryl-opens-ml/workshop-monitoring:main
          env:
          - name: ARGILLA_URI
            value: "http://data-labeling.default.svc.cluster.local:6900"
          - name: ARGILLA_KEY
            value: "adminadmin"
          - name: ARGILLA_NAMESPACE
            value: "admin"
          - name: SERVING_URL
            value: "http://serving-custom-model.default.svc.cluster.local:80"
          - name: FEEDBACK_DATASET_NAME
            value: "workshop-feedback-custom-model"


---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-custom
  labels:
    app: monitoring-custom
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: monitoring-custom