---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
        - name: main
          image: kyrylprojector/pipeline:latest
---
apiVersion: v1
kind: Service
metadata:
  name: pipeline
  labels:
    app: pipeline
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: pipeline