---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serving-custom-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serving-custom-model
  template:
    metadata:
      labels:
        app: serving-custom-model
    spec:
      containers:
        - name: main
          image: ghcr.io/huggingface/text-generation-inference:1.4.2
          args: ["--model-id", "kyryl-opens-ml/flan-t5-small-sql", "--num-shard", "1"]
          ports:
          - containerPort: 80
          volumeMounts:
          - name: shm
            mountPath: /dev/shm
          - name: data
            mountPath: /data
      volumes:
      - name: shm
        emptyDir:
          sizeLimit: 1Gi
      - name: data
        emptyDir:
          sizeLimit: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: serving-custom-model
  labels:
    app: serving-custom-model
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: serving-custom-model